---

- hosts: localhost
  become: yes
  vars:
    go_version: 1.22.0
    user_name: jbowe
    keys:
      - name: "boweflex_ed25519"
        mode: "0600"
      - name: "boweflex_ed25519.pub"
        mode: "0644"
    key_source: "./.ssh"
    key_dest: "{{ lookup('env', 'HOME') }}/.ssh"
  tasks:

    - name: SSH installation
      become_user: "{{ user_name }}"
      block:
        - name: Create ssh directory
          file:
            dest: "{{ key_dest }}"
            state: directory
            mode: 0700

        - name: Install ssh key
          copy:
            src: "{{ key_source }}/{{ item.name }}"
            dest: "{{ key_dest }}"
            mode: "{{ item.mode }}"
          loop: "{{ keys }}"

        - name: Copy config file
          copy:
            src: "{{ key_source }}/config"
            dest: "{{ key_dest }}"
      tags:
        - dotfiles
        - ssh 

    - name: Ensure prereqs are installed
      package:
        name:
          - git
          - software-properties-common
          - python3-apt
          - gpg
          - stow
        state: present
      tags:
        - dotfiles

    - name: Pull down dotfiles and subdirectories
      become_user: "{{ user_name }}"
      git:
        repo: git@github.com:BoweFlex/.dotfiles.git
        version: main
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
      tags:
        - dotfiles

    - name: Stow configuration block
      become_user: "{{ user_name }}"
      block:
        - name: Create directories for config files
          file:
            path: "{{ item }}"
            state: directory
          loop:
            - "{{ lookup('env', 'HOME') }}/.fonts"
            - "{{ lookup('env', 'HOME') }}/.config/alacritty"
            - "{{ lookup('env', 'HOME') }}/.config/picom"

        - name: Stow config files
          shell: "stow {{ item.package }} -d {{ lookup('env', 'HOME') }}/.dotfiles -t {{ item.target }}"
          loop:
            - { package: "zsh", target: "{{ lookup('env', 'HOME') }}" }
            - { package: "nvim", target: "{{ lookup('env', 'HOME') }}" }
            - { package: "alacritty", target: "{{ lookup('env', 'HOME') }}/.config/alacritty/" }
            - { package: "picom", target: "{{ lookup('env', 'HOME') }}/.config/picom/" }
            - { package: "tmux", target: "{{ lookup('env', 'HOME') }}" }
            - { package: "fonts", target: "{{ lookup('env', 'HOME') }}/.fonts" }
          tags:
            - dotfiles

    - name: Add ppa repo for neovim unstable
      apt_repository:
        repo: ppa:neovim-ppa/unstable

    - name: Update apt repositories
      package:
        name: "*"
        state: latest

    - name: Install other packages
      package:
        name:
          - zsh # Better terminal
          - vim 
          - neovim # More powerful vim
          - npm # Needed for mason.nvim
          - i3 # Window Manager
          - tmux # multiplexer for ssh and file editing
          - fzf # Fuzzy finder, using for tmux
          - feh # Wallpaper handler for i3
          - alacritty # Prettier terminal
          - picom # Compositor for i3, needed for window transparency
          - pass # SRE Password manager
          - ripgrep # required for telescope.nvim
          - clamav
          - clamav-daemon
          - podman
          - python3-pip
          - ansible-lint
            # - vault
          - python3-venv
          - remmina
          - cheese
          - krb5-user
          - libkrb5-dev
          - python3-dev
          - python3.10-venv

    - name: Install oh-my-zsh
      become_user: "{{ user_name }}"
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
        depth: 1

    - name: Change user's shell to zsh
      user:
        name: "{{ user_name }}"
        shell: /usr/bin/zsh

    - name: Check if golang is installed
      stat:
        path: /usr/local/go/VERSION
      register: version_file

    - name: Block to check if golang is correct version
      block:
        - name: Read file contents
          set_fact: 
            contents: "{{ lookup('ansible.builtin.file', '/usr/local/go/VERSION') }}"
        - name: Check if version matches var
          set_fact: go_correct_version={{ contents | regex_findall(go_version) | first }}
          ignore_errors: yes # This fails if the correct version is not found, which is expected
      when: version_file.stat.exists

    - name: Block - Install golang if not already up to date
      block:
        - name: Remove existing go installation
          command: rm -rf /usr/local/go

        - name: Download go tar file
          command: wget https://go.dev/dl/go{{go_version}}.linux-amd64.tar.gz

        - name: Extract and move new go folder to /usr/local
          command: tar -C /usr/local -xzf go{{go_version}}.linux-amd64.tar.gz
          become: true

        - name: Delete downloaded go tar file
          shell: rm -rf go{{go_version}}.linux-amd64.tar.gz*
      when: go_correct_version is not defined or not version_file.stat.exists 

