---

- hosts: workstations
  become: yes
  roles:
    - ssh # Listed out of alphabetical order as things like dotfiles rely on this
    - common
    - dotfiles
    - git
    - gnome
    - golang
    - helix
    - zsh

...
