---

- name: Create directories for config files
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ lookup('env', 'HOME') }}/.fonts"
    - "{{ lookup('env', 'HOME') }}/.config/alacritty"
    - "{{ lookup('env', 'HOME') }}/.config/fontconfig"
    - "{{ lookup('env', 'HOME') }}/.config/picom"
    - "{{ lookup('env', 'HOME') }}/.config/helix"
    - "{{ lookup('env', 'HOME') }}/.config/wezterm"

- name: Stow config files
  shell: "stow {{ item.package }} -d {{ lookup('env', 'HOME') }}/.dotfiles -t {{ item.target }}"
  loop:
    - { package: "zsh", target: "{{ lookup('env', 'HOME') }}" }
    - { package: "nvim", target: "{{ lookup('env', 'HOME') }}" }
    - { package: "alacritty", target: "{{ lookup('env', 'HOME') }}/.config/alacritty/" }
    - { package: "picom", target: "{{ lookup('env', 'HOME') }}/.config/picom/" }
    - { package: "tmux", target: "{{ lookup('env', 'HOME') }}" }
    - { package: "fonts", target: "{{ lookup('env', 'HOME') }}/.fonts" }
    - { package: "fontconfig", target: "{{ lookup('env', 'HOME') }}/.config/fontconfig"}
    - { package: "helix", target: "{{ lookup('env', 'HOME') }}/.config/helix" }
    - { package: "wezterm", target: "{{ lookup('env', 'HOME') }}/.config/wezterm/" }

...
