---

- name: Configure Workspace Keybinds
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/{{ item.action }}-to-workspace-{{ workspace_num }}"
    value: "{{ item.keybind }}"
  loop:
    - action: move
      keybind: "['<Shift><Super>{{ workspace_num }}']"
    - action: switch
      keybind: "['<Super>{{ workspace_num }}']"

- name: Remove Redundant Keybinds
  community.general.dconf:
    key: "/org/gnome/shell/keybindings/switch-to-application-{{ workspace_num }}"
    value: "['']"

...
