---

- name: Import Dconf Setup
  ansible.builtin.import_tasks: dconf.yml
  tags:
    - dconf

- name: Import Custom Keybind Setup
  become_user: "{{ user_name }}"
  ansible.builtin.import_tasks: workspaces.yml
  tags:
    - dconf
    - workspaces

- name: Import Custom Power Settings
  become_user: "{{ user_name }}"
  ansible.builtin.import_tasks: power.yml
  tags:
    - dconf

...
