---

- name: Import Dconf Setup
  ansible.builtin.import_tasks: dconf.yml
  tags:
    - dconf

- name: Import Custom Keybind Setup
  ansible.builtin.import_tasks: keybinds.yml
  tags:
    - dconf

- name: Import Custom Power Settings
  ansible.builtin.import_tasks: power.yml
  tags:
    - dconf

...
