---

- name: Wezterm Apt Repository
  block:
    - name: Add Apt Key for Wezterm
      ansible.builtin.shell: curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg

    - name: Confirm Permissions for Apt Key
      ansible.builtin.file:
        path: /usr/share/keyrings/wezterm-fury.gpg
        mode: "0644"

    - name: Add Apt Repository for Wezterm
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
        filename: wezterm
        state: present

- name: Add ppa repo for neovim unstable
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: Add ppa repo for helix
  ansible.builtin.apt_repository:
    repo: ppa:maveonair/helix-editor

- name: Update repositories
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install other packages
  ansible.builtin.package:
    name:
      - zsh # Better terminal
      - vim 
      - wezterm-nightly # Terminal Emulator with builtin multiplexing
      - fd-find # "Better" find
      - neovim # More powerful vim
      - helix # Modal editor like vim
      - npm # Needed for mason.nvim
      - tmux # multiplexer for ssh and file editing
      - fzf # Fuzzy finder, using for tmux
      - feh # Wallpaper handler for i3
      - alacritty # Prettier terminal
      - picom # Compositor for i3, needed for window transparency
      - pass # SRE Password manager
      - ripgrep # required for telescope.nvim
      - podman # Docker but secure
      - ansible-lint
      - python3-venv
      - direnv
    state: latest

- name: Create Symlink for Fd
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/bin/fd
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link

...
